apiVersion: v1
kind: Pod
metadata:
  name: cm-test-pod
spec:
  containers:
  - name: cm-test
    image: busybox
    command: ['sh', '-c', "env | grep APP"]
    env:
    - name: APP_LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: cm-appvars
          key: appLogLevel
    - name: APP_DATA_DIR
      valueFrom:
        configMapKeyRef:
          name: cm-appvars
          key: appdatadir
  restartPolicy: Never